version: '3.8'


services:
  web:
    build: ./src
    command: |
      bash -c 'while !</dev/tcp/db/5432: do sleep 1: done: uvicorn app.main:app --reload --workers --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/:C:/Users/mojtaba/projects/fastapi-crud/src/app
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev
  
  db:
    image:  postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRESDB-hello_fastapi_dev

volumes:
  postgres_data: